export const keyToIcon: Record<string, string> = {
  Ctrl: '⌃',
  Command: '⌘',
  Shift: '⇧',
  Alt: '⌥',
  Backquote: '(',
  Backslash: '\\',
  BracketLeft: '[',
  BracketRight: ']',
  Comma: ',',
  Period: '.',
  Quote: '"',
  Equal: '=',
  Minus: '-',
  Plus: '+',
  Semicolon: ';',
  Slash: '/',
};

export const specialCharacters = [
  'Backquote',
  'Backslash',
  'BracketLeft',
  'BracketRight',
  'Comma',
  'Equal',
  'Minus',
  'Period',
  'Quote',
  'Semicolon',
  'Slash',
  'IntlBackslash',
  'IntlRo',
  'IntlYen',
];
